# Generated by Django 5.2.7 on 2025-10-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User Collection Name', max_length=60)),
                ('collectibles', models.ManyToManyField(related_name='collections', to='items.item')),
            ],
        ),
    ]
