# Generated by Django 5.2.7 on 2025-10-03 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Series Name', max_length=80)),
                ('release_date', models.DateField()),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='series', to='franchises.franchise')),
            ],
        ),
    ]
