# Generated by Django 5.2.7 on 2025-10-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to an image of this Labubu variant on the web', null=True),
        ),
    ]
