# Generated by Django 5.2.7 on 2025-10-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Franchise. Ex 'Labubu - The Monsters'", max_length=60)),
                ('brand', models.CharField(help_text='ex. POPMART', max_length=40)),
            ],
        ),
    ]
