# Generated by Django 5.2.7 on 2025-10-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE franchise_franchise RENAME TO franchises_franchise;",
            reverse_sql="ALTER TABLE franchises_franchise RENAME TO franchise_franchise;"
        ),
    ]
